baseURL = "https://radforschung.org/log/"
languageCode = "de-de"
pygmentsCodefences = true
pygmentsStyle = "native"
theme = "natrium"
title = "radforschung.log"
paginate = 50
[[menu.main]]
name = "@radforschung"
pre = "<i class='fa fa-twitter' title='twitter'></i>"
url = "https://twitter.com/radforschung"
[params]
description = ""
[params.logo]
alt = "radforschung"
height = "50"
title = "radforschung"
url = "logo.svg"
width = "50"
[permalinks]
page = "/:slug/"
post = "/:slug/"
[taxonomies]
category = "categories"
tag = "tags"
